#!/bin/sh
ARCH=$(uname -m)
OS=$(uname -s)
EXEC="bin/${OS}_${ARCH}/openocd"

if [ ! -x "${EXEC}" ]
then
    echo "No pre-built binary for $OS on $DARWIN ($EXEC)!"
    exit 1
fi

${EXEC} -f interface/ftdi/olimex-arm-usb-ocd-h.cfg -f interface/ftdi/olimex-arm-jtag-swd.cfg -f max78000.cfg -s tcl "$@"
