.PHONY: all
all:
	$(MAKE) -f Makefile.ARM
	$(MAKE) -f Makefile.RISCV

clean:
	$(MAKE) -f Makefile.ARM clean
	$(MAKE) -f Makefile.RISCV clean

distclean:
	$(MAKE) -f Makefile.ARM distclean
	$(MAKE) -f Makefile.RISCV distclean
