#!/bin/sh
DEVICE="MAX78000"
TARGET="sdk/Examples/$DEVICE/CNN"
COMMON_ARGS="--device $DEVICE --compact-data --mexpress --timer 0 --display-checkpoint"

./ai8xize.py --verbose --log --test-dir $TARGET --prefix mnist --checkpoint-file trained/ai85-mnist-qat8-q.pth.tar --config-file networks/mnist-chw-ai85.yaml --softmax $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix mnist-riscv --checkpoint-file trained/ai85-mnist-qat8-q.pth.tar --config-file networks/mnist-chw-ai85.yaml --softmax $COMMON_ARGS --riscv --riscv-debug "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix cifar-10 --checkpoint-file trained/ai85-cifar10-qat8-q.pth.tar --config-file networks/cifar10-hwc-ai85.yaml --softmax $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix cifar-100 --checkpoint-file trained/ai85-cifar100-qat8-q.pth.tar --config-file networks/cifar100-simple.yaml --softmax $COMMON_ARGS --boost 2.5 "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix cifar-100-mixed --checkpoint-file trained/ai85-cifar100-qat-mixed-q.pth.tar --config-file networks/cifar100-simple.yaml --softmax $COMMON_ARGS --boost 2.5 "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix cifar-100-simplewide2x-mixed --checkpoint-file trained/ai85-cifar100-simplenetwide2x-qat-mixed-q.pth.tar --config-file networks/cifar100-simplewide2x.yaml --softmax $COMMON_ARGS --boost 2.5 "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix cifar-100-residual --checkpoint-file trained/ai85-cifar100-residual-qat8-q.pth.tar --config-file networks/cifar100-ressimplenet.yaml --softmax $COMMON_ARGS --boost 2.5 "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix kws20 --checkpoint-file trained/ai85-kws20-qat8-q.pth.tar --config-file networks/kws20-hwc.yaml --softmax $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix kws20_v2 --checkpoint-file trained/ai85-kws20_v2-qat8-q.pth.tar --config-file networks/kws20-v2-hwc.yaml --softmax $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix kws20_v3 --checkpoint-file trained/ai85-kws20_v3-qat8-q.pth.tar --config-file networks/kws20-v3-hwc.yaml --softmax $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix faceid --checkpoint-file trained/ai85-faceid-qat8-q.pth.tar --config-file networks/faceid.yaml --fifo $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix cats-dogs --checkpoint-file trained/ai85-catsdogs-qat8-q.pth.tar --config-file networks/cats-dogs-chw.yaml --softmax $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpadd-minimal --checkpoint-file tests/test-mp_add_minimized_q.pth.tar --config-file tests/test-mpadd-minimal.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpadd-128 --config-file tests/test-mpadd-128.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpadd-192 --config-file tests/test-mpadd-192.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpadd-256 --config-file tests/test-mpadd-256.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpadd3-192 --config-file tests/test-mpadd3-192.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpadd3-256 --config-file tests/test-mpadd3-256.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpflatten-128 --config-file tests/test-mpflatten-128.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpflatten-192 --config-file tests/test-mpflatten-256.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mpflatten-256 --config-file tests/test-mpflatten-256.yaml $COMMON_ARGS "$@"
./ai8xize.py --verbose --log --test-dir $TARGET --prefix test-mppool-1x1 --config-file tests/test-mppool-1x1.yaml $COMMON_ARGS "$@"
